service: client-rewards
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: '*'
  apiGateway:
    apiKeys:
      - free: myFreeApiKey
    usagePlan:
      - free:
          quota:
            limit: 5
            period: DAY

plugins:
  - serverless-offline

functions:
  checkin:
    handler: src/automation/function/rewards-checkin.handler
    events:
      - httpApi:
          path: /rewards/checkin
          method: GET